<?php
/** Auto-generated from inc/customizer.php by panel_gen.py — do not hand-edit. */
defined('ABSPATH') || exit;

function ph_panel_tabs() {
    return [
        'contact' => ['title' => 'اطلاعات تماس و نقشه', 'icon' => 'dashicons-phone'],
        'social' => ['title' => 'شبکه‌های اجتماعی', 'icon' => 'dashicons-share'],
        'home' => ['title' => 'صفحه اصلی', 'icon' => 'dashicons-admin-home'],
        'mega' => ['title' => 'بنرهای مگامنو', 'icon' => 'dashicons-menu'],
        'footer' => ['title' => 'فوتر', 'icon' => 'dashicons-layout'],
        'shop' => ['title' => 'فروشگاه و ارسال', 'icon' => 'dashicons-cart'],
        'slider' => ['title' => 'اسلایدر نرم‌افزار', 'icon' => 'dashicons-images-alt2'],
        'pages' => ['title' => 'برگه‌های داخلی', 'icon' => 'dashicons-admin-page'],
        'pay' => ['title' => 'پرداخت و پیامک', 'icon' => 'dashicons-money'],
        'status' => ['title' => 'وضعیت سیستم', 'icon' => 'dashicons-info'],
    ];
}

function ph_panel_fields() {
    return [
        'ph_phone_display' => ['tab' => 'contact', 'label' => 'شماره تماس (نمایشی)', 'type' => 'text', 'default' => '۰۹۱۲ ۰۲۴ ۱۱۲۰', 'san' => 'sanitize_text_field', 'g' => 'اطلاعات تماس'],
        'ph_phone_tel' => ['tab' => 'contact', 'label' => 'شماره تماس (لینک tel، لاتین)', 'type' => 'text', 'default' => '+989120241120', 'san' => 'sanitize_text_field', 'g' => 'اطلاعات تماس'],
        'ph_email' => ['tab' => 'contact', 'label' => 'ایمیل', 'type' => 'text', 'default' => 'info@pejvakhesab.ir', 'san' => 'sanitize_text_field', 'g' => 'اطلاعات تماس'],
        'ph_address' => ['tab' => 'contact', 'label' => 'آدرس', 'type' => 'textarea', 'default' => 'اردبیل، بزرگراه شهید سلیمانی، میدان مادر، دفتر مرکزی پژواک حساب', 'san' => 'sanitize_textarea_field', 'g' => 'اطلاعات تماس'],
        'ph_address_short' => ['tab' => 'contact', 'label' => 'آدرس کوتاه (صفحه اصلی)', 'type' => 'text', 'default' => 'اردبیل، میدان مادر', 'san' => 'sanitize_text_field', 'g' => 'اطلاعات تماس'],
        'ph_hours' => ['tab' => 'contact', 'label' => 'ساعات کاری', 'type' => 'text', 'default' => 'شنبه تا پنجشنبه ۹ تا ۱۸', 'san' => 'sanitize_text_field', 'g' => 'اطلاعات تماس'],
        'ph_footer_about' => ['tab' => 'contact', 'label' => 'متن معرفی فوتر', 'type' => 'textarea', 'default' => 'مجموعه تخصصی ارائه‌دهنده نرم‌افزارهای حسابداری، تجهیزات فروشگاهی و راهکارهای یکپارچه فروش؛ از مشاوره و انتخاب تا نصب، آموزش و پشتیبانی در کنار کسب‌وکار شما هستیم.', 'san' => 'sanitize_textarea_field', 'g' => 'اطلاعات تماس'],
        'ph_map_url' => ['tab' => 'contact', 'label' => 'لینک مسیریابی نقشه', 'type' => 'url', 'default' => '#', 'san' => 'esc_url_raw', 'g' => 'نقشه'],
        'ph_map_embed' => ['tab' => 'contact', 'label' => 'کد جاسازی نقشه (iframe)', 'type' => 'textarea', 'default' => '', 'san' => 'ph_sanitize_iframe', 'g' => 'نقشه'],
        'ph_social_instagram' => ['tab' => 'social', 'label' => 'اینستاگرام', 'type' => 'url', 'default' => '#', 'san' => 'esc_url_raw', 'g' => ''],
        'ph_social_telegram' => ['tab' => 'social', 'label' => 'تلگرام', 'type' => 'url', 'default' => '#', 'san' => 'esc_url_raw', 'g' => ''],
        'ph_social_whatsapp' => ['tab' => 'social', 'label' => 'واتساپ', 'type' => 'url', 'default' => '#', 'san' => 'esc_url_raw', 'g' => ''],
        'ph_social_linkedin' => ['tab' => 'social', 'label' => 'لینکدین', 'type' => 'url', 'default' => '#', 'san' => 'esc_url_raw', 'g' => ''],
        'ph_hero_title' => ['tab' => 'home', 'label' => 'تیتر اصلی (هیرو)', 'type' => 'textarea', 'default' => 'راهکارهای هوشمند برای <span class="hl">حسابداری</span> و <span class="hl">فروشگاه</span> شما', 'san' => 'wp_kses_post', 'g' => 'هیرو (بخش اول)'],
        'ph_hero_sub' => ['tab' => 'home', 'label' => 'زیرعنوان هیرو', 'type' => 'textarea', 'default' => 'از نرم‌افزار حسابداری تا تجهیزات فروشگاهی؛ هر آنچه برای مدیریت حرفه‌ای کسب‌وکار خود نیاز دارید، در پژواک حساب.', 'san' => 'sanitize_textarea_field', 'g' => 'هیرو (بخش اول)'],
        'ph_hero_eyebrow' => ['tab' => 'home', 'label' => 'برچسب بالای تیتر', 'type' => 'text', 'default' => 'نرم‌افزار حسابداری · تجهیزات فروشگاهی · راهکار یکپارچه', 'san' => 'sanitize_text_field', 'g' => 'هیرو (بخش اول)'],
        'ph_hero_points' => ['tab' => 'home', 'label' => 'نکات هیرو (هر خط یکی)', 'type' => 'textarea', 'default' => "ضمانت اصالت کالا\nنصب و آموزش\nپشتیبانی تخصصی", 'san' => 'sanitize_textarea_field', 'g' => 'هیرو (بخش اول)'],
        'ph_hero_image' => ['tab' => 'home', 'label' => 'تصویر هیرو', 'type' => 'image', 'default' => '', 'san' => 'sanitize_text_field', 'g' => 'هیرو (بخش اول)'],
        'ph_hero_stat_labels' => ['tab' => 'home', 'label' => 'برچسب شمارنده‌ها (۳ خط)', 'type' => 'textarea', 'default' => "نرم‌افزار تخصصی\nدسته تجهیزات\nراهکار صنفی", 'san' => 'sanitize_textarea_field', 'g' => 'هیرو (بخش اول)'],
        'ph_float_1t' => ['tab' => 'home', 'label' => 'کارت شناور ۱ — تیتر', 'type' => 'text', 'default' => 'فاکتور #۱۲۴۸ صادر شد', 'san' => 'sanitize_text_field', 'g' => 'کارت‌های شناور'],
        'ph_float_1s' => ['tab' => 'home', 'label' => 'کارت شناور ۱ — زیرعنوان', 'type' => 'text', 'default' => 'نرم‌افزار باران · صندوق ۱', 'san' => 'sanitize_text_field', 'g' => 'کارت‌های شناور'],
        'ph_float_2t' => ['tab' => 'home', 'label' => 'کارت شناور ۲ — تیتر', 'type' => 'text', 'default' => '٪۱۸ رشد فروش ماه', 'san' => 'sanitize_text_field', 'g' => 'کارت‌های شناور'],
        'ph_float_2s' => ['tab' => 'home', 'label' => 'کارت شناور ۲ — زیرعنوان', 'type' => 'text', 'default' => 'گزارش مدیریتی لحظه‌ای', 'san' => 'sanitize_text_field', 'g' => 'کارت‌های شناور'],
        'ph_float_3t' => ['tab' => 'home', 'label' => 'کارت شناور ۳ — تیتر', 'type' => 'text', 'default' => 'فیش‌پرینتر متصل است', 'san' => 'sanitize_text_field', 'g' => 'کارت‌های شناور'],
        'ph_float_3s' => ['tab' => 'home', 'label' => 'کارت شناور ۳ — زیرعنوان', 'type' => 'text', 'default' => 'آماده چاپ فاکتور', 'san' => 'sanitize_text_field', 'g' => 'کارت‌های شناور'],
        'ph_trust_title' => ['tab' => 'home', 'label' => 'نوار اعتماد — تیتر', 'type' => 'text', 'default' => 'راهکار تخصصی کسب‌وکارهای فروشگاهی', 'san' => 'sanitize_text_field', 'g' => 'نوار اعتماد'],
        'ph_trust_items' => ['tab' => 'home', 'label' => 'نوار اعتماد (هر خط: آیکون|متن)', 'type' => 'textarea', 'default' => "users|مشاوره تخصصی\nshield|ضمانت اصالت کالا\nheadset|پشتیبانی فنی\nwrench|نصب و راه‌اندازی\ntruck|ارسال سریع\naward|خدمات پس از فروش", 'san' => 'sanitize_textarea_field', 'g' => 'نوار اعتماد'],
        'ph_sec_cats_eye' => ['tab' => 'home', 'label' => 'سربرگ «دسته‌بندی‌ها» — برچسب', 'type' => 'text', 'default' => 'دسته‌بندی محصولات', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_cats_title' => ['tab' => 'home', 'label' => 'سربرگ «دسته‌بندی‌ها» — تیتر', 'type' => 'text', 'default' => 'هر چیزی که برای مدیریت فروشگاه نیاز دارید', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_cats_sub' => ['tab' => 'home', 'label' => 'سربرگ «دسته‌بندی‌ها» — زیرعنوان', 'type' => 'textarea', 'default' => 'از نرم‌افزار تا سخت‌افزار؛ یک تأمین‌کننده مطمئن برای همه نیازهای فروشگاهی شما', 'san' => 'sanitize_textarea_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_soft_eye' => ['tab' => 'home', 'label' => 'سربرگ «نرم‌افزارها» — برچسب', 'type' => 'text', 'default' => 'نرم‌افزارهای حسابداری', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_soft_title' => ['tab' => 'home', 'label' => 'سربرگ «نرم‌افزارها» — تیتر', 'type' => 'text', 'default' => 'نرم‌افزار حسابداری مناسب کسب‌وکار شما', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_soft_sub' => ['tab' => 'home', 'label' => 'سربرگ «نرم‌افزارها» — زیرعنوان', 'type' => 'textarea', 'default' => 'راهکارهای تخصصی برای اصناف مختلف؛ با دمو، آموزش و پشتیبانی واقعی', 'san' => 'sanitize_textarea_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_wiz_eye' => ['tab' => 'home', 'label' => 'سربرگ «پیشنهادگر» — برچسب', 'type' => 'text', 'default' => 'راهنمای هوشمند انتخاب', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_wiz_title' => ['tab' => 'home', 'label' => 'سربرگ «پیشنهادگر» — تیتر', 'type' => 'text', 'default' => 'کدام نرم‌افزار برای من مناسب است؟', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_wiz_sub' => ['tab' => 'home', 'label' => 'سربرگ «پیشنهادگر» — زیرعنوان', 'type' => 'textarea', 'default' => 'به ۴ سؤال کوتاه پاسخ دهید تا مناسب‌ترین نرم‌افزار را پیشنهاد دهیم', 'san' => 'sanitize_textarea_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_hw_eye' => ['tab' => 'home', 'label' => 'سربرگ «تجهیزات» — برچسب', 'type' => 'text', 'default' => 'تجهیزات فروشگاهی', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_hw_title' => ['tab' => 'home', 'label' => 'سربرگ «تجهیزات» — تیتر', 'type' => 'text', 'default' => 'تجهیزات حرفه‌ای برای فروش سریع‌تر', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_hw_sub' => ['tab' => 'home', 'label' => 'سربرگ «تجهیزات» — زیرعنوان', 'type' => 'textarea', 'default' => 'تجهیزات اصلی با ضمانت شرکتی، تست‌شده و سازگار با نرم‌افزار شما', 'san' => 'sanitize_textarea_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_ready_eye' => ['tab' => 'home', 'label' => 'سربرگ «سیستم آماده» — برچسب', 'type' => 'text', 'default' => 'سیستم‌های آماده', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_ready_title' => ['tab' => 'home', 'label' => 'سربرگ «سیستم آماده» — تیتر', 'type' => 'text', 'default' => 'سیستم فروشگاهی آماده؛ فقط وصل کنید و شروع کنید', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_ready_sub' => ['tab' => 'home', 'label' => 'سربرگ «سیستم آماده» — زیرعنوان', 'type' => 'textarea', 'default' => 'یک پکیج کامل، تست‌شده و آماده‌به‌کار؛ بدون دردسر سازگاری و نصب', 'san' => 'sanitize_textarea_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_sol_eye' => ['tab' => 'home', 'label' => 'سربرگ «راهکارها» — برچسب', 'type' => 'text', 'default' => 'راهکار صنفی', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_sol_title' => ['tab' => 'home', 'label' => 'سربرگ «راهکارها» — تیتر', 'type' => 'text', 'default' => 'راهکار مناسب هر کسب‌وکار', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_sol_sub' => ['tab' => 'home', 'label' => 'سربرگ «راهکارها» — زیرعنوان', 'type' => 'textarea', 'default' => 'برای صنف خود، ترکیب آماده نرم‌افزار و تجهیزات را ببینید', 'san' => 'sanitize_textarea_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_why_eye' => ['tab' => 'home', 'label' => 'سربرگ «چرا ما» — برچسب', 'type' => 'text', 'default' => 'مزیت رقابتی', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_why_title' => ['tab' => 'home', 'label' => 'سربرگ «چرا ما» — تیتر', 'type' => 'text', 'default' => 'چرا پژواک حساب؟', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_why_sub' => ['tab' => 'home', 'label' => 'سربرگ «چرا ما» — زیرعنوان', 'type' => 'textarea', 'default' => 'ما فقط فروشنده نیستیم؛ شریک راه‌اندازی و رشد فروشگاه شما هستیم', 'san' => 'sanitize_textarea_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_brands_title' => ['tab' => 'home', 'label' => 'سربرگ «برندها» — تیتر', 'type' => 'text', 'default' => 'همکاران نرم‌افزاری و سخت‌افزاری ما', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_cmp_title' => ['tab' => 'home', 'label' => 'سربرگ «نوار مقایسه» — تیتر', 'type' => 'text', 'default' => 'محصولات را با هم مقایسه کنید', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_cmp_sub' => ['tab' => 'home', 'label' => 'سربرگ «نوار مقایسه» — زیرعنوان', 'type' => 'textarea', 'default' => 'دو یا سه محصول را انتخاب کنید و مشخصات فنی، قیمت و امکانات را کنار هم ببینید.', 'san' => 'sanitize_textarea_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_testi_eye' => ['tab' => 'home', 'label' => 'سربرگ «نظرات» — برچسب', 'type' => 'text', 'default' => 'نظر مشتریان', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_testi_title' => ['tab' => 'home', 'label' => 'سربرگ «نظرات» — تیتر', 'type' => 'text', 'default' => 'کسب‌وکارهایی که به پژواک حساب اعتماد کرده‌اند', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_blog_eye' => ['tab' => 'home', 'label' => 'سربرگ «مجله» — برچسب', 'type' => 'text', 'default' => 'مجله پژواک حساب', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_blog_title' => ['tab' => 'home', 'label' => 'سربرگ «مجله» — تیتر', 'type' => 'text', 'default' => 'آموزش و راهنمای خرید', 'san' => 'sanitize_text_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_sec_blog_sub' => ['tab' => 'home', 'label' => 'سربرگ «مجله» — زیرعنوان', 'type' => 'textarea', 'default' => 'مطالب کاربردی برای انتخاب درست نرم‌افزار و تجهیزات', 'san' => 'sanitize_textarea_field', 'g' => 'سربرگ بخش‌ها'],
        'ph_ready_price_label' => ['tab' => 'home', 'label' => 'سیستم آماده — برچسب قیمت', 'type' => 'text', 'default' => 'شروع قیمت سیستم‌های آماده', 'san' => 'sanitize_text_field', 'g' => 'سیستم آماده'],
        'ph_ready_list' => ['tab' => 'home', 'label' => 'سیستم آماده — اقلام (هر خط: آیکون|متن)', 'type' => 'textarea', 'default' => "cpu|کیس یا Mini PC\nmonitor|مانیتور لمسی\nscan|بارکدخوان\nprinter|فیش پرینتر\narchive|کشوی پول\nchart|نرم‌افزار حسابداری", 'san' => 'sanitize_textarea_field', 'g' => 'سیستم آماده'],
        'ph_wiz_title' => ['tab' => 'home', 'label' => 'پیشنهادگر — تیتر ستون', 'type' => 'text', 'default' => 'پیشنهادگر نرم‌افزار', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_sub' => ['tab' => 'home', 'label' => 'پیشنهادگر — توضیح ستون', 'type' => 'textarea', 'default' => 'بر اساس نوع کسب‌وکار، تعداد کاربران و نیازهای شما، بهترین گزینه را معرفی می‌کنیم.', 'san' => 'sanitize_textarea_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_steps' => ['tab' => 'home', 'label' => 'پیشنهادگر — مراحل (۴ خط)', 'type' => 'textarea', 'default' => "نوع کسب‌وکار\nتعداد کاربران\nحجم فروش\nانبارداری", 'san' => 'sanitize_textarea_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_q1t' => ['tab' => 'home', 'label' => 'پیشنهادگر — سؤال ۱ تیتر', 'type' => 'text', 'default' => 'نوع کسب‌وکار شما چیست؟', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_q1s' => ['tab' => 'home', 'label' => 'پیشنهادگر — سؤال ۱ راهنما', 'type' => 'text', 'default' => 'یکی از گزینه‌ها را انتخاب کنید', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_q2t' => ['tab' => 'home', 'label' => 'پیشنهادگر — سؤال ۲ تیتر', 'type' => 'text', 'default' => 'چند کاربر همزمان نیاز دارید؟', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_q2s' => ['tab' => 'home', 'label' => 'پیشنهادگر — سؤال ۲ راهنما', 'type' => 'text', 'default' => 'تعداد صندوق و کاربران سیستم', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_q3t' => ['tab' => 'home', 'label' => 'پیشنهادگر — سؤال ۳ تیتر', 'type' => 'text', 'default' => 'حجم فروش روزانه شما چقدر است؟', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_q3s' => ['tab' => 'home', 'label' => 'پیشنهادگر — سؤال ۳ راهنما', 'type' => 'text', 'default' => 'میانگین تعداد فاکتور در روز', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_q4t' => ['tab' => 'home', 'label' => 'پیشنهادگر — سؤال ۴ تیتر', 'type' => 'text', 'default' => 'آیا به انبارداری نیاز دارید؟', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_q4s' => ['tab' => 'home', 'label' => 'پیشنهادگر — سؤال ۴ راهنما', 'type' => 'text', 'default' => 'مدیریت موجودی، چندانبار و انبارگردانی', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_done_t' => ['tab' => 'home', 'label' => 'پیشنهادگر — تیتر نتیجه', 'type' => 'text', 'default' => 'پیشنهاد ما برای شما آماده شد', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_wiz_done_s' => ['tab' => 'home', 'label' => 'پیشنهادگر — متن نتیجه', 'type' => 'text', 'default' => 'بر اساس پاسخ‌های شما، این نرم‌افزار بهترین گزینه است:', 'san' => 'sanitize_text_field', 'g' => 'پیشنهادگر هوشمند'],
        'ph_cta_title' => ['tab' => 'home', 'label' => 'دعوت نهایی — تیتر', 'type' => 'text', 'default' => 'برای کسب‌وکار شما چه راهکاری مناسب است؟', 'san' => 'sanitize_text_field', 'g' => 'دعوت نهایی'],
        'ph_cta_sub' => ['tab' => 'home', 'label' => 'دعوت نهایی — متن', 'type' => 'textarea', 'default' => 'اگر برای انتخاب نرم‌افزار یا تجهیزات فروشگاهی مطمئن نیستید، کارشناسان پژواک حساب آماده راهنمایی شما هستند.', 'san' => 'sanitize_textarea_field', 'g' => 'دعوت نهایی'],
        'ph_mega_sw_t' => ['tab' => 'mega', 'label' => 'بنر نرم‌افزار — تیتر', 'type' => 'text', 'default' => 'در انتخاب نرم‌افزار مطمئن نیستید؟', 'san' => 'sanitize_text_field', 'g' => 'بنر نرم‌افزار'],
        'ph_mega_sw_s' => ['tab' => 'mega', 'label' => 'بنر نرم‌افزار — متن', 'type' => 'textarea', 'default' => 'کارشناسان پژواک حساب رایگان راهنمایی‌تان می‌کنند.', 'san' => 'sanitize_textarea_field', 'g' => 'بنر نرم‌افزار'],
        'ph_mega_hw_t' => ['tab' => 'mega', 'label' => 'بنر تجهیزات — تیتر', 'type' => 'text', 'default' => 'سیستم آماده فروشگاهی', 'san' => 'sanitize_text_field', 'g' => 'بنر تجهیزات'],
        'ph_mega_hw_s' => ['tab' => 'mega', 'label' => 'بنر تجهیزات — متن', 'type' => 'textarea', 'default' => 'فقط وصل کنید و شروع کنید؛ با نصب و آموزش رایگان.', 'san' => 'sanitize_textarea_field', 'g' => 'بنر تجهیزات'],
        'ph_mega_sol_t' => ['tab' => 'mega', 'label' => 'بنر راهکارها — تیتر', 'type' => 'text', 'default' => 'راهکار مناسب کسب‌وکار شما؟', 'san' => 'sanitize_text_field', 'g' => 'بنر راهکارها'],
        'ph_mega_sol_s' => ['tab' => 'mega', 'label' => 'بنر راهکارها — متن', 'type' => 'textarea', 'default' => 'در ۲ دقیقه، نرم‌افزار مناسب خود را پیدا کنید.', 'san' => 'sanitize_textarea_field', 'g' => 'بنر راهکارها'],
        'ph_foot_t2' => ['tab' => 'footer', 'label' => 'ستون ۲ — تیتر', 'type' => 'text', 'default' => 'دسترسی سریع', 'san' => 'sanitize_text_field', 'g' => 'ستون‌ها و متن'],
        'ph_foot_t3' => ['tab' => 'footer', 'label' => 'ستون ۳ — تیتر', 'type' => 'text', 'default' => 'نرم‌افزارها', 'san' => 'sanitize_text_field', 'g' => 'ستون‌ها و متن'],
        'ph_foot_nl_t' => ['tab' => 'footer', 'label' => 'خبرنامه — تیتر', 'type' => 'text', 'default' => 'عضویت در خبرنامه', 'san' => 'sanitize_text_field', 'g' => 'خبرنامه'],
        'ph_foot_nl_s' => ['tab' => 'footer', 'label' => 'خبرنامه — متن', 'type' => 'textarea', 'default' => 'آموزش‌ها، تخفیف‌ها و راهنمای خرید تجهیزات را دریافت کنید.', 'san' => 'sanitize_textarea_field', 'g' => 'خبرنامه'],
        'ph_foot_chips' => ['tab' => 'footer', 'label' => 'نشان‌های اعتماد (هر خط: آیکون|متن)', 'type' => 'textarea', 'default' => "shield|ضمانت اصالت کالا\ntruck|ارسال به سراسر کشور\nheadset|پشتیبانی تخصصی", 'san' => 'sanitize_textarea_field', 'g' => 'ستون‌ها و متن'],
        'ph_foot_copy' => ['tab' => 'footer', 'label' => 'متن کپی‌رایت ({year} = سال)', 'type' => 'textarea', 'default' => '© {year} پژواک حساب — تمامی حقوق محفوظ است.', 'san' => 'sanitize_textarea_field', 'g' => 'ستون‌ها و متن'],
        'ph_terms_url' => ['tab' => 'footer', 'label' => 'لینک قوانین و مقررات (خالی = خودکار)', 'type' => 'url', 'default' => '', 'san' => 'esc_url_raw', 'g' => 'لینک‌های حقوقی'],
        'ph_privacy_url' => ['tab' => 'footer', 'label' => 'لینک حریم خصوصی (خالی = خودکار)', 'type' => 'url', 'default' => '', 'san' => 'esc_url_raw', 'g' => 'لینک‌های حقوقی'],
        'ph_ship_std_t' => ['tab' => 'shop', 'label' => 'ارسال عادی — عنوان', 'type' => 'text', 'default' => 'ارسال عادی (۲ تا ۴ روز)', 'san' => 'sanitize_text_field', 'g' => 'روش‌های ارسال'],
        'ph_ship_std_d' => ['tab' => 'shop', 'label' => 'ارسال عادی — توضیح', 'type' => 'text', 'default' => 'بیمه + بسته‌بندی ایمن', 'san' => 'sanitize_text_field', 'g' => 'روش‌های ارسال'],
        'ph_ship_std_p' => ['tab' => 'shop', 'label' => 'ارسال عادی — هزینه (تومان)', 'type' => 'text', 'default' => '350000', 'san' => 'sanitize_text_field', 'g' => 'روش‌های ارسال'],
        'ph_ship_exp_t' => ['tab' => 'shop', 'label' => 'ارسال فوری — عنوان', 'type' => 'text', 'default' => 'ارسال فوری تهران (۲۴ ساعته)', 'san' => 'sanitize_text_field', 'g' => 'روش‌های ارسال'],
        'ph_ship_exp_d' => ['tab' => 'shop', 'label' => 'ارسال فوری — توضیح', 'type' => 'text', 'default' => 'فقط تهران و کرج', 'san' => 'sanitize_text_field', 'g' => 'روش‌های ارسال'],
        'ph_ship_exp_p' => ['tab' => 'shop', 'label' => 'ارسال فوری — هزینه (تومان)', 'type' => 'text', 'default' => '550000', 'san' => 'sanitize_text_field', 'g' => 'روش‌های ارسال'],
        'ph_ship_pick_t' => ['tab' => 'shop', 'label' => 'تحویل حضوری — عنوان', 'type' => 'text', 'default' => 'تحویل حضوری + نصب', 'san' => 'sanitize_text_field', 'g' => 'روش‌های ارسال'],
        'ph_ship_pick_d' => ['tab' => 'shop', 'label' => 'تحویل حضوری — توضیح', 'type' => 'text', 'default' => 'هماهنگی نصب در محل · رایگان', 'san' => 'sanitize_text_field', 'g' => 'روش‌های ارسال'],
        'ph_ship_freeover' => ['tab' => 'shop', 'label' => 'رایگان شدن ارسال عادی از مبلغ (تومان)', 'type' => 'text', 'default' => '50000000', 'san' => 'sanitize_text_field', 'g' => 'روش‌های ارسال'],
        'ph_coupon_code' => ['tab' => 'shop', 'label' => 'کد تخفیف', 'type' => 'text', 'default' => 'PEJVAK10', 'san' => 'sanitize_text_field', 'g' => 'کد تخفیف'],
        'ph_coupon_off' => ['tab' => 'shop', 'label' => 'درصد تخفیف کد', 'type' => 'text', 'default' => '10', 'san' => 'sanitize_text_field', 'g' => 'کد تخفیف'],
        'ph_warranty' => ['tab' => 'shop', 'label' => 'متن گارانتی (جدول مقایسه)', 'type' => 'text', 'default' => '۱۲ تا ۱۸ ماه + پشتیبانی', 'san' => 'sanitize_text_field', 'g' => 'عمومی فروشگاه'],
        'ph_search_tags' => ['tab' => 'shop', 'label' => 'جستجوهای پرتکرار (هر خط یکی)', 'type' => 'textarea', 'default' => "فیش پرینتر\nباران\nبارکدخوان\nصندوق\nلیبل", 'san' => 'sanitize_textarea_field', 'g' => 'عمومی فروشگاه'],
        'ph_provinces' => ['tab' => 'shop', 'label' => 'فهرست استان‌ها (هر خط یکی)', 'type' => 'textarea', 'default' => "تهران\nالبرز\nاصفهان\nفارس\nخراسان رضوی\nخوزستان\nآذربایجان شرقی\nآذربایجان غربی\nمازندران\nگیلان\nکرمان\nقم\nهرمزگان\nسیستان و بلوچستان\nکردستان\nکرمانشاه\nلرستان\nمرکزی\nهمدان\nزنجان\nسمنان\nیزد\nاردبیل\nقزوین\nگلستان\nایلام\nبوشهر\nچهارمحال و بختیاری\nکهگیلویه و بویراحمد\nخراسان شمالی\nخراسان جنوبی", 'san' => 'sanitize_textarea_field', 'g' => 'عمومی فروشگاه'],
        'ph_slider_per_desktop' => ['tab' => 'slider', 'label' => 'تعداد کارت در دسکتاپ', 'type' => 'text', 'default' => '3', 'san' => 'sanitize_text_field', 'g' => 'تنظیمات نمایش'],
        'ph_slider_per_tablet' => ['tab' => 'slider', 'label' => 'تعداد کارت در تبلت', 'type' => 'text', 'default' => '2', 'san' => 'sanitize_text_field', 'g' => 'تنظیمات نمایش'],
        'ph_slider_per_mobile' => ['tab' => 'slider', 'label' => 'تعداد کارت در موبایل', 'type' => 'text', 'default' => '1', 'san' => 'sanitize_text_field', 'g' => 'تنظیمات نمایش'],
        'ph_slider_autoplay' => ['tab' => 'slider', 'label' => 'پخش خودکار', 'type' => 'checkbox', 'default' => '', 'san' => 'ph_sanitize_checkbox', 'g' => 'رفتار اسلایدر'],
        'ph_slider_delay' => ['tab' => 'slider', 'label' => 'تأخیر پخش خودکار (میلی‌ثانیه)', 'type' => 'text', 'default' => '5000', 'san' => 'sanitize_text_field', 'g' => 'رفتار اسلایدر'],
        'ph_slider_loop' => ['tab' => 'slider', 'label' => 'چرخش بی‌پایان (Loop)', 'type' => 'checkbox', 'default' => '', 'san' => 'ph_sanitize_checkbox', 'g' => 'رفتار اسلایدر'],
        'ph_slider_dots' => ['tab' => 'slider', 'label' => 'نمایش نقطه‌های ناوبری', 'type' => 'checkbox', 'default' => '1', 'san' => 'ph_sanitize_checkbox', 'g' => 'رفتار اسلایدر'],
        'ph_sol_steps' => ['tab' => 'pages', 'label' => 'راهکار — مراحل (هر خط: تیتر|متن)', 'type' => 'textarea', 'default' => "مشاوره و نیازسنجی|شناخت دقیق کسب‌وکار و پیشنهاد بهینه‌ترین ترکیب نرم‌افزار و تجهیزات.\nتأمین و آماده‌سازی|تأمین تجهیزات اصلی، نصب نرم‌افزار و تست کامل قبل از ارسال.\nنصب و آموزش|نصب در محل، ورود اطلاعات پایه و آموزش کامل پرسنل.\nپشتیبانی مستمر|پشتیبانی فنی، به‌روزرسانی و خدمات پس از فروش دائمی.", 'san' => 'sanitize_textarea_field', 'g' => 'راهکار'],
        'ph_hw_check' => ['tab' => 'pages', 'label' => 'تجهیزات — چک‌لیست خدمات (هر خط: تیتر|متن)', 'type' => 'textarea', 'default' => "بررسی سازگاری رایگان|قبل از خرید، سازگاری با نرم‌افزار و سیستم شما چک می‌شود.\nتست قبل از ارسال|هر دستگاه قبل از ارسال روشن، تست و پیکربندی می‌شود.\nنصب و راه‌اندازی|نصب حضوری یا ریموت با آموزش کامل کار با دستگاه.\nگارانتی و قطعات|گارانتی شرکتی ۱۲ تا ۱۸ ماهه + تأمین قطعات.", 'san' => 'sanitize_textarea_field', 'g' => 'تجهیزات'],
        'ph_sw_dash' => ['tab' => 'pages', 'label' => 'نرم‌افزار — آمار داشبورد (هر خط: مقدار|برچسب)', 'type' => 'textarea', 'default' => "248M|فروش امروز\n1324|فاکتور امروز\n٪18|رشد ماهانه", 'san' => 'sanitize_textarea_field', 'g' => 'نرم‌افزار'],
        'ph_about_exp' => ['tab' => 'pages', 'label' => 'درباره ما — عدد تجربه', 'type' => 'text', 'default' => '+۱۰', 'san' => 'sanitize_text_field', 'g' => 'درباره ما'],
        'ph_about_exp_label' => ['tab' => 'pages', 'label' => 'درباره ما — برچسب تجربه', 'type' => 'text', 'default' => 'سال تجربه صنفی', 'san' => 'sanitize_text_field', 'g' => 'درباره ما'],
        'ph_about_story' => ['tab' => 'pages', 'label' => 'درباره ما — متن داستان', 'type' => 'textarea', 'default' => 'پژواک حساب با تمرکز بر دو حوزه به‌هم‌پیوسته شکل گرفت: نرم‌افزارهای حسابداری و تجهیزات فروشگاهی. ما باور داریم فروشگاه مدرن، به یک راهکار یکپارچه نیاز دارد؛ نه چند تکه جدا از هم. به همین دلیل، از مشاوره و انتخاب تا تأمین، نصب، آموزش و پشتیبانی را یکجا ارائه می‌کنیم.', 'san' => 'sanitize_textarea_field', 'g' => 'درباره ما'],
        'ph_about_checks' => ['tab' => 'pages', 'label' => 'درباره ما — چک‌لیست (هر خط یکی)', 'type' => 'textarea', 'default' => "تخصص همزمان در نرم‌افزار و سخت‌افزار فروشگاهی\nراهکار آماده برای ۸ صنف مختلف\nضمانت اصالت کالا و گارانتی شرکتی\nپشتیبانی فنی واقعی توسط کارشناس متخصص", 'san' => 'sanitize_textarea_field', 'g' => 'درباره ما'],
        'ph_about_values' => ['tab' => 'pages', 'label' => 'درباره ما — ارزش‌ها (هر خط: آیکون|تیتر|متن)', 'type' => 'textarea', 'default' => "shield|صداقت در پیشنهاد|اگر محصولی به درد شما نخورد، صریح می‌گوییم؛ حتی به قیمت از دست دادن فروش.\nwrench|تخصص واقعی|تیم فنی ما خودش نصب می‌کند، آموزش می‌دهد و پشتیبانی می‌کند.\nheadset|همراهی بلندمدت|رابطه ما با تحویل کالا تمام نمی‌شود؛ تازه شروع می‌شود.", 'san' => 'sanitize_textarea_field', 'g' => 'درباره ما'],
        'ph_contact_support' => ['tab' => 'pages', 'label' => 'تماس — کارت پشتیبانی (تیتر|سطر۱|سطر۲)', 'type' => 'textarea', 'default' => "پشتیبانی فنی|تلفنی و ریموت؛ پاسخگویی در ساعات کاری|قراردادهای سازمانی: پشتیبانی ویژه", 'san' => 'sanitize_textarea_field', 'g' => 'تماس'],
        'ph_contact_form_t' => ['tab' => 'pages', 'label' => 'تماس — تیتر فرم', 'type' => 'text', 'default' => 'ارسال پیام', 'san' => 'sanitize_text_field', 'g' => 'تماس'],
        'ph_contact_form_s' => ['tab' => 'pages', 'label' => 'تماس — توضیح فرم', 'type' => 'text', 'default' => 'فرم زیر را تکمیل کنید؛ حداکثر ظرف یک روز کاری پاسخ می‌دهیم.', 'san' => 'sanitize_text_field', 'g' => 'تماس'],
        'ph_svc_cta_t' => ['tab' => 'pages', 'label' => 'خدمات — تیتر دعوت نهایی', 'type' => 'text', 'default' => 'به کدام خدمت نیاز دارید؟', 'san' => 'sanitize_text_field', 'g' => 'خدمات'],
        'ph_svc_cta_s' => ['tab' => 'pages', 'label' => 'خدمات — متن دعوت نهایی', 'type' => 'text', 'default' => 'درخواست خود را ثبت کنید تا کارشناسان ما با شما تماس بگیرند.', 'san' => 'sanitize_text_field', 'g' => 'خدمات'],
        'ph_sol_cta_t' => ['tab' => 'pages', 'label' => 'راهکار — تیتر دعوت نهایی', 'type' => 'text', 'default' => 'راه‌اندازی صنف شما، تخصص ماست', 'san' => 'sanitize_text_field', 'g' => 'راهکار'],
        'ph_sol_cta_s' => ['tab' => 'pages', 'label' => 'راهکار — متن دعوت نهایی', 'type' => 'text', 'default' => 'همین امروز مشاوره بگیرید و ترکیب بهینه نرم‌افزار و تجهیزات را بشناسید.', 'san' => 'sanitize_text_field', 'g' => 'راهکار'],
        'ph_sw_cta_t' => ['tab' => 'pages', 'label' => 'نرم‌افزار — تیتر دعوت نهایی', 'type' => 'text', 'default' => 'هنوز مطمئن نیستید؟ دمو ببینید', 'san' => 'sanitize_text_field', 'g' => 'نرم‌افزار'],
        'ph_sw_cta_s' => ['tab' => 'pages', 'label' => 'نرم‌افزار — متن دعوت نهایی', 'type' => 'text', 'default' => 'جلسه معرفی آنلاین رایگان؛ نرم‌افزار را با سناریوی واقعی کسب‌وکار خودتان ببینید.', 'san' => 'sanitize_text_field', 'g' => 'نرم‌افزار'],
        'ph_sms_enabled' => ['tab' => 'pay', 'label' => 'فعال‌سازی ورود پیامکی (ملی پیامک)', 'type' => 'checkbox', 'default' => '', 'san' => 'ph_sanitize_checkbox', 'g' => ''],
        'ph_sms_user' => ['tab' => 'pay', 'label' => 'نام کاربری ملی پیامک', 'type' => 'text', 'default' => '', 'san' => 'sanitize_text_field', 'g' => ''],
        'ph_sms_pass' => ['tab' => 'pay', 'label' => 'رمز عبور ملی پیامک', 'type' => 'password', 'default' => '', 'san' => 'sanitize_text_field', 'g' => ''],
        'ph_sms_from' => ['tab' => 'pay', 'label' => 'شماره فرستنده پیامک', 'type' => 'text', 'default' => '', 'san' => 'sanitize_text_field', 'g' => ''],
        'ph_sms_pattern' => ['tab' => 'pay', 'label' => 'کد پترن (BodyId) — خالی = ارسال متن ساده', 'type' => 'text', 'default' => '', 'san' => 'sanitize_text_field', 'g' => ''],
        'ph_sms_paid' => ['tab' => 'pay', 'label' => 'پیامک «پرداخت موفق» به مشتری', 'type' => 'checkbox', 'default' => '', 'san' => 'ph_sanitize_checkbox', 'g' => ''],
        'ph_zarin_enabled' => ['tab' => 'pay', 'label' => 'فعال‌سازی پرداخت آنلاین (زرین‌پال)', 'type' => 'checkbox', 'default' => '', 'san' => 'ph_sanitize_checkbox', 'g' => ''],
        'ph_zarin_merchant' => ['tab' => 'pay', 'label' => 'مرچنت‌کد زرین‌پال', 'type' => 'text', 'default' => '', 'san' => 'sanitize_text_field', 'g' => ''],
        'ph_zarin_sandbox' => ['tab' => 'pay', 'label' => 'حالت آزمایشی زرین‌پال (سندباکس)', 'type' => 'checkbox', 'default' => '', 'san' => 'ph_sanitize_checkbox', 'g' => ''],
    ];
}
